name: 'test'
on: workflow_dispatch

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: Get GitHub Project V2 Items
        id: get-github-project-v2-items
        uses: ./
        with:
          gh_token: ${{ steps.generate-token.outputs.token }} # required
          project_number: 1 # required
          repo: 'eleutheria-tech/dummy-repo'
          single_select_field_id: 'PVTSSF_lADOBsfKuc4AGINOzgDiC2o'
          single_select_field_option_id: '98236657'
          label_name: 'v0.0.1'

      - run: |
          echo ${{ toJSON(steps.get-github-project-v2-items.outputs.item_ids_json) }}
